name: waka-stats.yml

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Disable "This Week I Spent My Time On" settings
          SHOW_TIMEZONE: "false"
          SHOW_LANGUAGE: "false"
          SHOW_EDITORS: "false"
          SHOW_PROJECTS: "false"
          SHOW_OS: "false"

          # Disable other settings
          SHOW_TOTAL_CODE_TIME: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_UPDATED_DATE: 'False'
          SHOW_LOC_CHART: 'False'